apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  selector:
    app: {{ .Values.selector }}
  type: ClusterIP
  ports:
    - name: tomcat
      protocol: TCP
      targetPort: 8080
      port: 8080
