apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: 
      app: {{ .Values.selector_matchlabels }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: {{ .Values.deployment_name }}
      labels:
        app: {{ .Values.selector_matchlabels }}
    spec:
      containers:
      - name: {{ .Values.deployment_name }}
